services:
  mongodb:
    container_name: 'mongo'
    image: 'mongo:5.0'
    environment:
      MONGO_INITDB_DATABASE: availability
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - .env
    ports:
      - 27017:27017
