server:
  port: 8081
spring:
  application:
    name: starv.micro.availability
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/availability
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      data-locations: classpath:db/data.json
      mode: always
  config:
    import: classpath:eureka.yml













