eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/availability
  application:
    name: starv.micro.availability
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      data-locations: classpath:db/data.json
      mode: always
server:
  port: 8010
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'














