server:
  port: 8081
spring:
  application:
    name: starv.micro.availability
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/availability
  config:
    import: classpath:eureka.yml













